apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: twrxc3cjc-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-8b16aeb90d.8vpp.p3.openshiftapps.com/rhtap/rhtap-qe-dotnet-basic:d97993b0243e530bd73621e5972b7f2c9712de57@sha256:e5180baf9af719f600da739037e525d54e795e8569a73d6190fec9849ce85057
          name: container-image
